services:
  mysql:
    image: mysql:8.1
    container_name: mysql_fipe
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fipe_db
      MYSQL_USER: fipe_user
      MYSQL_PASSWORD: fipe_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: redis_fipe
    ports:
      - "6379:6379"

volumes:
  mysql_data: