spring:
  application:
    name: API2
  datasource:
    url: jdbc:mysql://localhost:3306/fipe_db
    username: fipe_user
    password: fipe_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
